version: '3'

services:

  sonarqube:
    image: sonarqube:6.7.6-community
    ports:
      - '80:9000/tcp'
    environment:
      sonar.jdbc.username: sonar
      sonar.jdbc.password: sonar
      sonar.jdbc.url: jdbc:postgresql://sonarqube-db:5432/sonar
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs
    depends_on:
      - sonarqube-db

  sonarqube-db:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonarqube-db:/var/lib/postgresql
      - sonarqube-db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'


volumes:
  sonarqube-conf:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
  sonarqube-db:
  sonarqube-db-data:

